const env = import.meta.env;

const NODE_MODE = env.VITE_ENV_MODE || "";

const API_ORIGIN = env.VITE_API_ORIGIN || "";
const API_ENDPOINT = env.VITE_API_ENDPOINT || "";

const APP_ORIGIN = env.VITE_ORIGIN;

const ADMINISTRATOR_ROLE = env.VITE_ADMINISTRATOR_ROLE || "";

const FIREBASE_API_KEY = env.VITE_FIREBASE_API_KEY || "";
const FIREBASE_AUTH_DOMAIN = env.VITE_FIREBASE_AUTH_DOMAIN || "";
const FIREBASE_PROJECT_ID = env.VITE_FIREBASE_PROJECT_ID || "";
const FIREBASE_STORAGE_BUCKET = env.VITE_FIREBASE_STORAGE_BUCKET || "";
const FIREBASE_MESSAGING_SENDER_ID =
  env.VITE_FIREBASE_MESSAGING_SENDER_ID || "";
const FIREBASE_APP_ID = env.VITE_FIREBASE_APP_ID || "";
const FIREBASE_MEASUREMENT_ID = env.VITE_FIREBASE_MEASUREMENT_ID || "";

export {
  NODE_MODE,
  API_ORIGIN,
  API_ENDPOINT,
  APP_ORIGIN,
  // FIREBASE
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
  ADMINISTRATOR_ROLE,
};
